light_mode_menu_background_color:
  type: string
  default: ""
  description: 
    en: "Side-bar background light mode color in hexadecimal, css color name or Discourse color variable. Leave blank to use current default."
    
light_mode_menu_transparency:
  type: integer
  default: ""
  description: 
    en: "Light mode background transparency scale 0.0-1.0 (ie: 0.1 = 10%, 0.75 = 75%)."
  
dark_mode_menu_background_color:
  type: string
  default: ""
  description: 
    en: "Side-bar background dark mode color in hexadecimal, css color name or Discourse color variable. Leave blank to use current default."

dark_mode_menu_transparency:
  type: integer
  default: ""
  description: 
    en: "Dark mode background transparency scale 0.0-1.0 (ie: 0.1 = 10%, 0.75 = 75%)."
  
light_mode_header_font_color:
  type: string
  default: ""
  description: 
    en: "Light mode section headers font color. Leave blank to use current default."

dark_mode_header_font_color:
  type: string
  default: ""
  description: 
    en: "Dark mode section headers font color. Leave blank to use current default."

header_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: 
    en: "Section headers font weight."

header_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: 
    en: "Section headers text size in px. Leave blank to use current default."
  
light_mode_link_font_color:
  type: string
  default: ""
  description: 
    en: "Light mode link font color. Leave blank to use current default."
    
dark_mode_link_font_color:
  type: string
  default: ""
  description: 
    en: "Dark mode link font color. Leave blank to use current default."

header_font_weight:
  type: enum
  default: normal
  choices:
    - normal
    - bold
  description: 
    en: "Section headers font weight."

link_font_size:
  type: enum
  default: ""
  choices:
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  description: 
    en: "Section links text size in px. Leave blank to use current default."

light_mode_link_icon_color:
  type: string
  default: ""
  description: 
    en: "Light mode color of side-bar link icons. Leave blank to use current default."

dark_mode_link_icon_color:
  type: string
  default: ""
  description: 
    en: "Dark mode color of side-bar link icons. Leave blank to use current default."
  
hide_category_bullets:
  type: bool
  default: false
  description: 
    en: "Hide the Category bullets in the side-bar."

category_bullet_rounding:
  type: enum
  default: ""
  choices:
    - 10%
    - 20%
    - 30%
    - 40%
    - 50%
  description: 
    en: "Side-bar category bullet rounding. Blank = default square, 50% = circle."
